language: elixir
elixir:
  - 1.3.4
  - 1.4.5
  - 1.5.2
otp_release:
  - 18.3
  - 19.0
  - 20.0
addons:
  postgresql: "9.4"
sudo: false # to use faster container based build environment
before_script:
  - psql -c 'create database plasm_test;' -U postgres
script:
  - mix deps.get
  - MIX_ENV=test mix test.setup
  - mix test
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
